name: the_gorgeous_login
description: The Gorgeous Login UI
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  font_awesome_flutter:
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
    path: ../

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/icon/loginpage.png"
  image_path_ios: "assets/icon/loginpage.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf